/**
 * GENERATED by scripts/discover-models.ts — DO NOT EDIT BY HAND.
 * Derived from perchai-cli@2.4.101 (dist/perch.mjs, read 2026-09-15)
 * cross-referenced against the Starter pool at https://www.perchai.app/docs/concepts/models (docs = pool truth).
 */
/** User agent the Perch server gates on (client_update_required). */
export const PERCH_CLI_VERSION = "2.4.101";
export const PERCH_CLI_UA = `perchai-cli/2.4.101`;
