/**
 * GENERATED by scripts/discover-models.ts — DO NOT EDIT BY HAND.
 * Derived from perchai-cli@2.4.101 (dist/perch.mjs, read 2026-09-15)
 * cross-referenced against the Starter pool at https://www.perchai.app/docs/concepts/models (docs = pool truth).
 */
/** Bare pi model id -> Starter-pool pin and registry facts. */
export interface GeneratedPerchModel {
	pin: string;
	displayName: string;
	contextWindow: number;
	maxOutputTokens: number;
	reasoning: boolean;
}

export const PERCH_MODEL_PINS: Record<string, GeneratedPerchModel> = {
	"gpt-5.6-luna": {
		pin: "azure-foundry-gpt-5-6-luna",
		displayName: "GPT-5.6 Luna",
		contextWindow: 1050000,
		maxOutputTokens: 128000,
		reasoning: true,
	},
	"qwen-3.6": {
		pin: "wandb-qwen3-6-35b-a3b",
		displayName: "Qwen 3.6",
		contextWindow: 262144,
		maxOutputTokens: 8192,
		reasoning: true,
	},
	"kimi-2.5": {
		pin: "bedrock-mantle-moonshotai-kimi-k2-5",
		displayName: "Kimi K2.5",
		contextWindow: 256000,
		maxOutputTokens: 16000,
		reasoning: false,
	},
	"glm-5": {
		pin: "bedrock-mantle-zai-glm-5",
		displayName: "GLM 5",
		contextWindow: 200000,
		maxOutputTokens: 32000,
		reasoning: true,
	},
	"qwen3-coder": {
		pin: "bedrock-mantle-qwen-qwen3-coder-480b-a35b-instruct",
		displayName: "Qwen3 Coder",
		contextWindow: 128000,
		maxOutputTokens: 32000,
		reasoning: true,
	},
	"nemotron-super": {
		pin: "bedrock-mantle-nvidia-nemotron-super-3-120b",
		displayName: "Nemotron Super",
		contextWindow: 256000,
		maxOutputTokens: 32000,
		reasoning: true,
	},
	"gemma-4-e2b": {
		pin: "bedrock-mantle-google-gemma-4-e2b",
		displayName: "Gemma 4 E2B",
		contextWindow: 128000,
		maxOutputTokens: 16000,
		reasoning: true,
	},
	"gemma-4-31b": {
		pin: "bedrock-mantle-google-gemma-4-31b",
		displayName: "Gemma 4 31B",
		contextWindow: 256000,
		maxOutputTokens: 32000,
		reasoning: true,
	},
};
